// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "./auth";
import SessionWrapper from "./SessionWrapper"; // Adjust path if needed
import {  Provider } from "@/components";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" className="h-screen w-full">
  <body className={cn(inter.className, "bg-white", "h-full")}>

        <SessionWrapper session={session}>
          <Provider> 
          <Navbar/>
          {children}
          <Toaster/>
          </Provider>
      
        </SessionWrapper>
      </body>
    </html>
  );
}
