import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
// import {Amplify} from "aws-amplify"
// import {ConfigureAmplify} from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* Disable browser extension interference in development */}
        {process.env.NODE_ENV === 'development' && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                Object.defineProperty(window, 'BIS', { value: null });
                Object.defineProperty(document, 'bis_skin_checked', { value: null });
              `,
            }}
          />
        )}

<div className="flex gap-6 px-6 py-4 bg-blue-600 text-white font-semibold text-lg shadow-md">
  <Link href="/" prefetch={false} className="hover:text-blue-200 transition">
    Home
  </Link>
  <Link href="/user" prefetch={false} className="hover:text-blue-200 transition">
    User
  </Link>
</div>
        
        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
